## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file criptografia.sagetex.sage
from sage.all_cmdline import *   # import sage library
## This file (criptografia.sagetex.sage) was *autogenerated* from criptografia.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('criptografia', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.endofdoc()
